name: 'DevCycle Secrets Manager'
description: 'Set GitHub Secrets securely from AWS Secrets Manager'

inputs:
  secrets_map:
    description: 'A JSON object of environment variables mapped to AWS Secrets Manager secret names'
    required: true
  role_prefix:
    description: 'The prefix of the role to assume in the target AWS account'
    required: true
    default: 'GitHub-Actions-'
  aws_region:
    description: 'The AWS region where the secrets are stored'
    required: true
    default: 'us-east-1'
  aws_account_id:
    description: 'The AWS account ID where the secrets are stored'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{inputs.aws_account_id}}:role/${{inputs.role_prefix}}-${{ github.event.repository.name }}
        aws-region: ${{ inputs.aws_region }}
    - name: Set Secrets
      shell: bash
      run: |
        echo "${{ inputs.secrets_map }}" | jq -r 'to_entries[] | "\(.key) \(.value)"' | while IFS=' ' read -r key value; do
          secret_value=$(aws secretsmanager get-secret-value --secret-id "$value" --query SecretString --output text)    
          echo "::add-mask::$secret_value"
          echo "$key=$secret_value" >> $GITHUB_ENV
        done
