name: 'DevCycle Secrets Manager'
description: 'Set GitHub Secrets securely from AWS Secrets Manager'

inputs:
  secrets_map:
    description: 'A JSON object of environment variables mapped to AWS Secrets Manager secret names'
    required: true
  role_prefix:
    description: 'The prefix of the role to assume in the target AWS account'
    required: true
    default: 'GitHub-Actions-'
  aws_region:
    description: 'The AWS region where the secrets are stored'
    required: true
    default: 'us-east-1'
  aws_account_id:
    description: 'The AWS account ID where the secrets are stored'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{inputs.aws_account_id}}:role/${{inputs.role_prefix}}-${{ github.event.repository.name }}
        aws-region: ${{ inputs.aws_region }}
    - name: Set Secrets
      shell: bash
      run: |
        echo "${{ inputs.secrets_map }}" > secrets_map.json
        export $(jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" secrets_map.json)
        for key in $(jq -r 'keys[]' secrets_map.json); do
          secret_name=$(jq -r --arg key "$key" '.[$key]' secrets_map.json)
          secret_value=$(aws secretsmanager get-secret-value --secret-id "${{ secrets[secret_name] }}" --query SecretString --output text)        
          echo "::add-mask::$(aws secretsmanager get-secret-value --secret-id "${{ secrets[secret_name] }}" --query SecretString --output text)"
          echo "$key=$secret_value" >> $GITHUB_ENV
        done
        rm secrets_map.json
